"""empty message

Revision ID: 013735a9866d
Revises: 5fd16895747c
Create Date: 2020-05-31 20:58:37.080536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '013735a9866d'
down_revision = '5fd16895747c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
