"""empty message

Revision ID: b3ccb837d1b1
Revises: 013735a9866d
Create Date: 2020-05-31 21:00:20.578445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3ccb837d1b1'
down_revision = '013735a9866d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
